name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - ci-publish-test

permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  id-token: write # to enable use of OIDC for trusted publishing and npm provenance

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - run: npm clean-install

      - name: Lint all packages
        run: npx turbo lint

      - name: Validate current commit with commitlint
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
      LIASE_SECRETS_FILE: ${{ vars.LIASE_SECRETS_FILE }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - run: npm clean-install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Test all packages
        # Use "-u" to ignore snapshot mismatches. Sites may occasionally return different values
        # over time or depending on requester-specific details like geographical location.
        run: npx turbo test -- -u

  publish:
    name: Publish ${{ matrix.package }}
    if: (github.event_name == 'push') && ((github.ref == 'refs/heads/main') || (github.ref == 'refs/heads/ci-publish-test'))
    runs-on: ubuntu-latest
    needs: [lint, test]
    strategy:
      matrix:
        package: [core, cli, example-plugin]
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm clean-install

      - name: Build
        run: npx turbo build --filter=@liase/${{ matrix.package }}

      - name: Verify provenance attestations and registry signatures
        run: npm audit signatures

      - name: Release
        working-directory: packages/${{ matrix.package }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

      - name: Print publish info
        working-directory: packages/${{ matrix.package }}
        run: |
          VERSION=$(jq -r '.version' package.json)
          if [[ ! "$VERSION" == 0.0.0* ]]; then
            prefix_message="Published new version of ${{ matrix.package }}:"
            echo -e "### :rocket: $prefix_message \n\`\`\`\n$VERSION\n\`\`\`" >> $GITHUB_STEP_SUMMARY
            echo -e "$prefix_message\n\e[1m$VERSION\e[0m"
          else
            message="No publishable changes made to ${{ matrix.package }} since last version"
            echo "### $message" >> $GITHUB_STEP_SUMMARY
            echo -e "\e[1m$message\e[0m"
          fi
